//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalBike
{
    using System;
    using System.Collections.Generic;
    
    public partial class Returned
    {
        public int RentID { get; set; }
        public Nullable<int> BikeID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public Nullable<decimal> TotalRent { get; set; }
        public string BikeModel { get; set; }
        public string CustomerName { get; set; }
    }
}
